sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        excluded_exceptions:
            - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
            - Symfony\Component\HttpKernel\Exception\BadRequestHttpException
            - Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException
            - Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
            - Symfony\Component\Security\Core\Exception\InsufficientAuthenticationException
            - Symfony\Component\Security\Core\Exception\AccessDeniedException
